// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module LoopMatmulLdB(
  input         clock,
                reset,
                io_req_valid,
  input  [15:0] io_req_bits_max_k,
                io_req_bits_max_j,
  input  [3:0]  io_req_bits_pad_k,
                io_req_bits_pad_j,
  input  [39:0] io_req_bits_dram_addr,
                io_req_bits_dram_stride,
  input         io_req_bits_transpose,
  input  [14:0] io_req_bits_addr_end,
  input         io_req_bits_loop_id,
                io_cmd_ready,
                io_rob_overloaded,
  output        io_req_ready,
                io_cmd_valid,
  output [63:0] io_cmd_bits_rs1,
                io_cmd_bits_rs2,
  output [15:0] io_k,
                io_j,
  output        io_idle,
                io_loop_id
);

  reg         state;	// @[LoopMatmul.scala:152:22]
  reg  [15:0] req_max_k;	// @[LoopMatmul.scala:154:16]
  reg  [15:0] req_max_j;	// @[LoopMatmul.scala:154:16]
  reg  [3:0]  req_pad_k;	// @[LoopMatmul.scala:154:16]
  reg  [3:0]  req_pad_j;	// @[LoopMatmul.scala:154:16]
  reg  [39:0] req_dram_addr;	// @[LoopMatmul.scala:154:16]
  reg  [39:0] req_dram_stride;	// @[LoopMatmul.scala:154:16]
  reg         req_transpose;	// @[LoopMatmul.scala:154:16]
  reg  [14:0] req_addr_end;	// @[LoopMatmul.scala:154:16]
  reg         req_loop_id;	// @[LoopMatmul.scala:154:16]
  reg  [15:0] k;	// @[LoopMatmul.scala:156:14]
  reg  [15:0] j;	// @[LoopMatmul.scala:157:14]
  wire [15:0] row_iterator = req_transpose ? j : k;	// @[LoopMatmul.scala:154:16, :156:14, :157:14, :159:25]
  wire [15:0] col_iterator = req_transpose ? k : j;	// @[LoopMatmul.scala:154:16, :156:14, :157:14, :160:25]
  wire [15:0] max_row_iterator = req_transpose ? req_max_j : req_max_k;	// @[LoopMatmul.scala:154:16, :162:29]
  wire [15:0] max_col_iterator = req_transpose ? req_max_k : req_max_j;	// @[LoopMatmul.scala:154:16, :163:29]
  wire [15:0] max_blocks = max_col_iterator < 16'h5 ? max_col_iterator : 16'h4;	// @[LoopMatmul.scala:163:29, :169:{23,36}]
  wire [28:0] _GEN = {14'h0, req_addr_end} - {{9'h0, req_max_k} * {9'h0, req_max_j}, 4'h0} + {{9'h0, row_iterator} * {9'h0, max_col_iterator} + {9'h0, col_iterator}, 4'h0};	// @[LoopMatmul.scala:154:16, :159:25, :160:25, :163:29, :171:{36,48}, :175:{31,47,66}, :177:43, :186:16]
  wire [15:0] blocks = col_iterator + max_blocks <= max_col_iterator ? max_blocks : max_col_iterator - col_iterator;	// @[LoopMatmul.scala:160:25, :163:29, :169:23, :176:{19,33,46,95}]
  wire        _io_cmd_valid_output = state & ~io_rob_overloaded;	// @[LoopMatmul.scala:152:22, :197:{34,37}]
  wire        _T = io_cmd_ready & _io_cmd_valid_output;	// @[Decoupled.scala:51:35, LoopMatmul.scala:197:34]
  wire [16:0] _next_j_T_3 = {1'h0, j} + {1'h0, req_transpose ? 16'h1 : max_blocks};	// @[LoopMatmul.scala:152:22, :154:16, :157:14, :169:23, :204:23, Util.scala:41:15]
  wire        _next_j_T_4 = _next_j_T_3 > {1'h0, req_max_j - 16'h1};	// @[LoopMatmul.scala:152:22, :154:16, Util.scala:39:28, :41:15, :43:17]
  wire [15:0] next_j = _next_j_T_4 ? 16'h0 : _next_j_T_3[15:0];	// @[Mux.scala:101:16, Util.scala:41:15, :43:17]
  wire [16:0] _next_k_T_4 = {1'h0, k} + {1'h0, req_transpose ? max_blocks : 16'h1};	// @[LoopMatmul.scala:152:22, :154:16, :156:14, :169:23, :204:23, :205:23, Util.scala:41:15]
  wire        _next_k_T_5 = _next_k_T_4 > {1'h0, req_max_k - 16'h1};	// @[LoopMatmul.scala:152:22, :154:16, Util.scala:39:28, :41:15, :43:17]
  wire        _T_4 = ~state & io_req_valid;	// @[Decoupled.scala:51:35, LoopMatmul.scala:152:22, :192:25]
  always @(posedge clock) begin
    if (reset)
      state <= 1'h0;	// @[LoopMatmul.scala:152:22]
    else
      state <= _T_4 | ~(_T & ~(|next_j) & ((|next_j) ? k : _next_k_T_5 ? 16'h0 : _next_k_T_4[15:0]) == 16'h0) & state;	// @[Decoupled.scala:51:35, LoopMatmul.scala:152:22, :156:14, :202:22, :208:58, :213:{36,45}, :214:13, :218:22, :220:11, Mux.scala:101:16, Util.scala:41:15, :43:17]
    if (_T_4) begin	// @[Decoupled.scala:51:35]
      req_max_k <= io_req_bits_max_k;	// @[LoopMatmul.scala:154:16]
      req_max_j <= io_req_bits_max_j;	// @[LoopMatmul.scala:154:16]
      req_pad_k <= io_req_bits_pad_k;	// @[LoopMatmul.scala:154:16]
      req_pad_j <= io_req_bits_pad_j;	// @[LoopMatmul.scala:154:16]
      req_dram_addr <= io_req_bits_dram_addr;	// @[LoopMatmul.scala:154:16]
      req_dram_stride <= io_req_bits_dram_stride;	// @[LoopMatmul.scala:154:16]
      req_transpose <= io_req_bits_transpose;	// @[LoopMatmul.scala:154:16]
      req_addr_end <= io_req_bits_addr_end;	// @[LoopMatmul.scala:154:16]
      req_loop_id <= io_req_bits_loop_id;	// @[LoopMatmul.scala:154:16]
      k <= 16'h0;	// @[LoopMatmul.scala:156:14, Mux.scala:101:16]
      j <= 16'h0;	// @[LoopMatmul.scala:157:14, Mux.scala:101:16]
    end
    else begin	// @[Decoupled.scala:51:35]
      if (~_T | (|next_j)) begin	// @[Decoupled.scala:51:35, LoopMatmul.scala:156:14, :202:22, :208:58, :211:7, Mux.scala:101:16]
      end
      else if (_next_k_T_5)	// @[Util.scala:43:17]
        k <= 16'h0;	// @[LoopMatmul.scala:156:14, Mux.scala:101:16]
      else	// @[Util.scala:43:17]
        k <= _next_k_T_4[15:0];	// @[LoopMatmul.scala:156:14, Util.scala:41:15]
      if (_T) begin	// @[Decoupled.scala:51:35]
        if (_next_j_T_4)	// @[Util.scala:43:17]
          j <= 16'h0;	// @[LoopMatmul.scala:157:14, Mux.scala:101:16]
        else	// @[Util.scala:43:17]
          j <= _next_j_T_3[15:0];	// @[LoopMatmul.scala:157:14, Util.scala:41:15]
      end
    end
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        state = _RANDOM_0[0];	// @[LoopMatmul.scala:152:22]
        req_max_k = _RANDOM_0[16:1];	// @[LoopMatmul.scala:152:22, :154:16]
        req_max_j = {_RANDOM_0[31:17], _RANDOM_1[0]};	// @[LoopMatmul.scala:152:22, :154:16]
        req_pad_k = _RANDOM_1[4:1];	// @[LoopMatmul.scala:154:16]
        req_pad_j = _RANDOM_1[8:5];	// @[LoopMatmul.scala:154:16]
        req_dram_addr = {_RANDOM_1[31:9], _RANDOM_2[16:0]};	// @[LoopMatmul.scala:154:16]
        req_dram_stride = {_RANDOM_2[31:17], _RANDOM_3[24:0]};	// @[LoopMatmul.scala:154:16]
        req_transpose = _RANDOM_3[25];	// @[LoopMatmul.scala:154:16]
        req_addr_end = {_RANDOM_3[31:26], _RANDOM_4[8:0]};	// @[LoopMatmul.scala:154:16]
        req_loop_id = _RANDOM_4[9];	// @[LoopMatmul.scala:154:16]
        k = _RANDOM_4[25:10];	// @[LoopMatmul.scala:154:16, :156:14]
        j = {_RANDOM_4[31:26], _RANDOM_5[9:0]};	// @[LoopMatmul.scala:154:16, :157:14]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  assign io_req_ready = ~state;	// @[LoopMatmul.scala:152:22, :192:25]
  assign io_cmd_valid = _io_cmd_valid_output;	// @[LoopMatmul.scala:197:34]
  assign io_cmd_bits_rs1 = {2'h0, {22'h0, req_dram_addr} + {2'h0, {40'h0, row_iterator} * {16'h0, req_dram_stride} + {40'h0, col_iterator} & 56'hFFFFFFF, 4'h0}};	// @[LoopMatmul.scala:154:16, :159:25, :160:25, :171:36, :173:{35,53}, :174:33, :177:43, :181:12, :183:16, :1083:17, Mux.scala:101:16]
  assign io_cmd_bits_rs2 = {11'h0, 5'h10 - {1'h0, max_row_iterator == max_row_iterator - 16'h1 ? (req_transpose ? req_pad_j : req_pad_k) : 4'h0}, 9'h0, {blocks[2:0], 4'h0} - {3'h0, col_iterator + blocks >= max_col_iterator ? (req_transpose ? req_pad_k : req_pad_j) : 4'h0}, 3'h0, _GEN[28:26], 11'h0, _GEN[14:0]};	// @[LocalAddr.scala:108:37, LoopMatmul.scala:152:22, :154:16, :160:25, :162:29, :163:29, :165:20, :166:20, :175:31, :176:19, :177:{38,43,57,66}, :178:{27,32,50,70}, :186:16, :190:32]
  assign io_k = k;	// @[LoopMatmul.scala:156:14]
  assign io_j = j;	// @[LoopMatmul.scala:157:14]
  assign io_idle = ~state;	// @[LoopMatmul.scala:152:22, :192:25]
  assign io_loop_id = req_loop_id;	// @[LoopMatmul.scala:154:16]
endmodule

