// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module SourceD(
  input          clock,
                 reset,
                 io_req_valid,
                 io_req_bits_prio_0,
                 io_req_bits_prio_2,
  input  [2:0]   io_req_bits_opcode,
                 io_req_bits_param,
                 io_req_bits_size,
  input  [5:0]   io_req_bits_source,
                 io_req_bits_offset,
                 io_req_bits_put,
  input  [9:0]   io_req_bits_set,
  input  [3:0]   io_req_bits_sink,
  input  [2:0]   io_req_bits_way,
  input          io_req_bits_bad,
                 io_d_ready,
                 io_pb_pop_ready,
  input  [127:0] io_pb_beat_data,
  input  [15:0]  io_pb_beat_mask,
  input          io_pb_beat_corrupt,
                 io_rel_pop_ready,
  input  [127:0] io_rel_beat_data,
  input          io_rel_beat_corrupt,
                 io_bs_radr_ready,
  input  [127:0] io_bs_rdat_data,
  input          io_bs_wadr_ready,
  input  [9:0]   io_evict_req_set,
  input  [2:0]   io_evict_req_way,
  input  [9:0]   io_grant_req_set,
  input  [2:0]   io_grant_req_way,
  output         io_req_ready,
                 io_d_valid,
  output [2:0]   io_d_bits_opcode,
  output [1:0]   io_d_bits_param,
  output [2:0]   io_d_bits_size,
  output [5:0]   io_d_bits_source,
  output [3:0]   io_d_bits_sink,
  output         io_d_bits_denied,
  output [127:0] io_d_bits_data,
  output         io_d_bits_corrupt,
                 io_pb_pop_valid,
  output [5:0]   io_pb_pop_bits_index,
  output         io_pb_pop_bits_last,
                 io_rel_pop_valid,
  output [5:0]   io_rel_pop_bits_index,
  output         io_rel_pop_bits_last,
                 io_bs_radr_valid,
  output [2:0]   io_bs_radr_bits_way,
  output [9:0]   io_bs_radr_bits_set,
  output [1:0]   io_bs_radr_bits_beat,
                 io_bs_radr_bits_mask,
  output         io_bs_wadr_valid,
  output [2:0]   io_bs_wadr_bits_way,
  output [9:0]   io_bs_wadr_bits_set,
  output [1:0]   io_bs_wadr_bits_beat,
                 io_bs_wadr_bits_mask,
  output [127:0] io_bs_wdat_data,
  output         io_evict_safe,
                 io_grant_safe
);

  wire [1:0]      s1_x_bypass;	// @[SourceD.scala:360:44]
  wire [63:0]     _s3_bypass_data_T_25;	// @[SourceD.scala:210:75]
  wire [63:0]     _s3_bypass_data_T_24;	// @[SourceD.scala:210:75]
  wire            s4_ready;	// @[SourceD.scala:293:59]
  wire            s3_ready;	// @[SourceD.scala:242:24]
  wire            s3_valid;	// @[SourceD.scala:241:23]
  wire [127:0]    _atomics_io_data_out;	// @[SourceD.scala:258:23]
  wire            _queue_io_enq_ready;	// @[SourceD.scala:120:21]
  wire            _queue_io_deq_valid;	// @[SourceD.scala:120:21]
  wire [127:0]    _queue_io_deq_bits_data;	// @[SourceD.scala:120:21]
  reg             busy;	// @[SourceD.scala:84:21]
  reg             s1_block_r;	// @[SourceD.scala:85:27]
  reg  [1:0]      s1_counter;	// @[SourceD.scala:86:27]
  reg             s1_req_reg_prio_0;	// @[Reg.scala:19:16]
  reg             s1_req_reg_prio_2;	// @[Reg.scala:19:16]
  reg  [2:0]      s1_req_reg_opcode;	// @[Reg.scala:19:16]
  reg  [2:0]      s1_req_reg_param;	// @[Reg.scala:19:16]
  reg  [2:0]      s1_req_reg_size;	// @[Reg.scala:19:16]
  reg  [5:0]      s1_req_reg_source;	// @[Reg.scala:19:16]
  reg  [5:0]      s1_req_reg_offset;	// @[Reg.scala:19:16]
  reg  [5:0]      s1_req_reg_put;	// @[Reg.scala:19:16]
  reg  [9:0]      s1_req_reg_set;	// @[Reg.scala:19:16]
  reg  [3:0]      s1_req_reg_sink;	// @[Reg.scala:19:16]
  reg  [2:0]      s1_req_reg_way;	// @[Reg.scala:19:16]
  reg             s1_req_reg_bad;	// @[Reg.scala:19:16]
  wire            s1_req_prio_0 = busy ? s1_req_reg_prio_0 : io_req_bits_prio_0;	// @[Reg.scala:19:16, SourceD.scala:84:21, :88:19]
  wire [2:0]      s1_req_opcode = busy ? s1_req_reg_opcode : io_req_bits_opcode;	// @[Reg.scala:19:16, SourceD.scala:84:21, :88:19]
  wire [2:0]      s1_req_size = busy ? s1_req_reg_size : io_req_bits_size;	// @[Reg.scala:19:16, SourceD.scala:84:21, :88:19]
  wire [2:0]      _GEN = busy ? s1_req_reg_offset[5:3] : io_req_bits_offset[5:3];	// @[Reg.scala:19:16, SourceD.scala:84:21, :88:19]
  wire [9:0]      s1_req_set = busy ? s1_req_reg_set : io_req_bits_set;	// @[Reg.scala:19:16, SourceD.scala:84:21, :88:19]
  wire [2:0]      s1_req_way = busy ? s1_req_reg_way : io_req_bits_way;	// @[Reg.scala:19:16, SourceD.scala:84:21, :88:19]
  wire            _s1_valid_T = busy | io_req_valid;	// @[SourceD.scala:84:21, :90:40]
  reg             s1_latch_bypass;	// @[SourceD.scala:90:32]
  reg  [1:0]      s1_bypass_r;	// @[Reg.scala:19:16]
  wire [1:0]      s1_mask = {s1_req_size[2] | _GEN[0], s1_req_size[2] | ~(_GEN[0])} & ~(s1_latch_bypass ? s1_x_bypass : s1_bypass_r);	// @[Cat.scala:33:92, Misc.scala:205:21, :209:26, :210:20, :214:29, Reg.scala:19:16, SourceD.scala:88:19, :90:32, :91:22, :92:{76,78}, :360:44]
  wire            _s1_single_T_2 = s1_req_opcode == 3'h6;	// @[SourceD.scala:88:19, :93:33]
  wire            s1_grant = _s1_single_T_2 & (busy ? s1_req_reg_param : io_req_bits_param) == 3'h2 | (&s1_req_opcode);	// @[Reg.scala:19:16, SourceD.scala:84:21, :88:19, :93:{33,50,66,76,93}, :282:84]
  wire            s1_need_r = (|s1_mask) & s1_req_prio_0 & s1_req_opcode != 3'h5 & ~s1_grant & ((|s1_req_opcode) | s1_req_size < 3'h3);	// @[SourceD.scala:88:19, :92:76, :93:76, :94:{27,66,78,88}, :95:{34,50,65}]
  wire            _io_bs_radr_valid_output = _s1_valid_T & s1_need_r & ~s1_block_r;	// @[SourceD.scala:85:27, :90:40, :94:88, :96:{56,59}]
  wire [1:0]      s1_beat = _GEN[2:1] | s1_counter;	// @[SourceD.scala:86:27, :88:19, :102:{32,56}]
  reg             queue_io_enq_valid_REG;	// @[SourceD.scala:121:40]
  reg             queue_io_enq_valid_REG_1;	// @[SourceD.scala:121:32]
  reg             s2_full;	// @[SourceD.scala:147:24]
  reg             s2_valid_pb;	// @[SourceD.scala:148:28]
  reg  [1:0]      s2_beat;	// @[Reg.scala:19:16]
  reg  [1:0]      s2_bypass;	// @[Reg.scala:19:16]
  reg             s2_req_prio_0;	// @[Reg.scala:19:16]
  reg             s2_req_prio_2;	// @[Reg.scala:19:16]
  reg  [2:0]      s2_req_opcode;	// @[Reg.scala:19:16]
  reg  [2:0]      s2_req_param;	// @[Reg.scala:19:16]
  reg  [2:0]      s2_req_size;	// @[Reg.scala:19:16]
  reg  [5:0]      s2_req_source;	// @[Reg.scala:19:16]
  reg  [5:0]      s2_req_offset;	// @[Reg.scala:19:16]
  reg  [5:0]      s2_req_put;	// @[Reg.scala:19:16]
  reg  [9:0]      s2_req_set;	// @[Reg.scala:19:16]
  reg  [3:0]      s2_req_sink;	// @[Reg.scala:19:16]
  reg  [2:0]      s2_req_way;	// @[Reg.scala:19:16]
  reg             s2_req_bad;	// @[Reg.scala:19:16]
  reg             s2_last;	// @[Reg.scala:19:16]
  reg             s2_need_r;	// @[Reg.scala:19:16]
  reg             s2_need_pb;	// @[Reg.scala:19:16]
  reg             s2_retires;	// @[Reg.scala:19:16]
  reg             s2_need_d;	// @[Reg.scala:19:16]
  reg  [127:0]    s2_pdata_r_data;	// @[Reg.scala:19:16]
  reg  [15:0]     s2_pdata_r_mask;	// @[Reg.scala:19:16]
  reg             s2_pdata_r_corrupt;	// @[Reg.scala:19:16]
  wire            pb_ready = s2_req_prio_0 ? io_pb_pop_ready : io_rel_pop_ready;	// @[Reg.scala:19:16, SourceD.scala:175:21]
  wire            s2_ready = ~s2_full | s3_ready & (~s2_valid_pb | pb_ready);	// @[SourceD.scala:147:24, :148:28, :175:21, :183:27, :184:{15,24,37,54}, :242:24]
  reg             s3_full;	// @[SourceD.scala:190:24]
  reg             s3_valid_d;	// @[SourceD.scala:191:27]
  reg  [1:0]      s3_beat;	// @[Reg.scala:19:16]
  reg  [1:0]      s3_bypass;	// @[Reg.scala:19:16]
  reg             s3_req_prio_0;	// @[Reg.scala:19:16]
  reg             s3_req_prio_2;	// @[Reg.scala:19:16]
  reg  [2:0]      s3_req_opcode;	// @[Reg.scala:19:16]
  reg  [2:0]      s3_req_param;	// @[Reg.scala:19:16]
  reg  [2:0]      s3_req_size;	// @[Reg.scala:19:16]
  reg  [5:0]      s3_req_source;	// @[Reg.scala:19:16]
  reg  [5:0]      s3_req_offset;	// @[Reg.scala:19:16]
  reg  [9:0]      s3_req_set;	// @[Reg.scala:19:16]
  reg  [3:0]      s3_req_sink;	// @[Reg.scala:19:16]
  reg  [2:0]      s3_req_way;	// @[Reg.scala:19:16]
  reg             s3_req_bad;	// @[Reg.scala:19:16]
  reg  [127:0]    s3_pdata_data;	// @[Reg.scala:19:16]
  reg  [15:0]     s3_pdata_mask;	// @[Reg.scala:19:16]
  reg             s3_pdata_corrupt;	// @[Reg.scala:19:16]
  reg             s3_need_bs;	// @[Reg.scala:19:16]
  reg             s3_retires;	// @[Reg.scala:19:16]
  reg             s3_need_r;	// @[Reg.scala:19:16]
  wire [127:0]    d_bits_data = {s3_bypass[1] ? _s3_bypass_data_T_25 : _queue_io_deq_bits_data[127:64], s3_bypass[0] ? _s3_bypass_data_T_24 : _queue_io_deq_bits_data[63:0]};	// @[Cat.scala:33:92, Reg.scala:19:16, SourceD.scala:120:21, :207:78, :208:78, :210:75]
  wire [7:0][2:0] _GEN_0 = {{3'h4}, {{2'h2, s3_req_param != 3'h2}}, {3'h2}, {3'h1}, {3'h1}, {3'h1}, {3'h0}, {3'h0}};	// @[Misc.scala:205:21, Reg.scala:19:16, SourceD.scala:214:{18,32}, :222:24, :280:84, :281:84, :282:84]
  wire [2:0]      d_bits_opcode = s3_req_prio_0 ? _GEN_0[s3_req_opcode] : 3'h6;	// @[Reg.scala:19:16, SourceD.scala:93:33, :222:24]
  wire            _T_30 = s3_valid & s4_ready;	// @[SourceD.scala:231:34, :241:23, :293:59]
  assign s3_valid = s3_full & (~s3_valid_d | io_d_ready);	// @[SourceD.scala:190:24, :191:27, :241:{23,27,39}]
  assign s3_ready = ~s3_full | s4_ready & (~s3_valid_d | io_d_ready);	// @[SourceD.scala:190:24, :191:27, :232:11, :241:27, :242:{24,37,53}, :293:59]
  reg             s4_full;	// @[SourceD.scala:248:24]
  reg  [1:0]      s4_beat;	// @[Reg.scala:19:16]
  reg             s4_need_bs;	// @[Reg.scala:19:16]
  reg             s4_need_pb;	// @[Reg.scala:19:16]
  reg             s4_req_prio_2;	// @[Reg.scala:19:16]
  reg  [2:0]      s4_req_param;	// @[Reg.scala:19:16]
  reg  [2:0]      s4_req_size;	// @[Reg.scala:19:16]
  reg  [5:0]      s4_req_offset;	// @[Reg.scala:19:16]
  reg  [9:0]      s4_req_set;	// @[Reg.scala:19:16]
  reg  [2:0]      s4_req_way;	// @[Reg.scala:19:16]
  reg  [2:0]      s4_adjusted_opcode;	// @[Reg.scala:19:16]
  reg  [127:0]    s4_pdata_data;	// @[Reg.scala:19:16]
  reg  [15:0]     s4_pdata_mask;	// @[Reg.scala:19:16]
  reg             s4_pdata_corrupt;	// @[Reg.scala:19:16]
  reg  [127:0]    s4_rdata;	// @[Reg.scala:19:16]
  assign s4_ready = ~s3_retires | ~s4_full | io_bs_wadr_ready | ~s4_need_bs;	// @[Reg.scala:19:16, SourceD.scala:248:24, :290:29, :293:{15,30,59}]
  reg  [2:0]      s5_req_size;	// @[Reg.scala:19:16]
  reg  [5:0]      s5_req_offset;	// @[Reg.scala:19:16]
  reg  [9:0]      s5_req_set;	// @[Reg.scala:19:16]
  reg  [2:0]      s5_req_way;	// @[Reg.scala:19:16]
  reg  [1:0]      s5_beat;	// @[Reg.scala:19:16]
  reg  [127:0]    s5_dat;	// @[Reg.scala:19:16]
  reg  [2:0]      s6_req_size;	// @[Reg.scala:19:16]
  reg  [5:0]      s6_req_offset;	// @[Reg.scala:19:16]
  reg  [9:0]      s6_req_set;	// @[Reg.scala:19:16]
  reg  [2:0]      s6_req_way;	// @[Reg.scala:19:16]
  reg  [1:0]      s6_beat;	// @[Reg.scala:19:16]
  reg  [127:0]    s6_dat;	// @[Reg.scala:19:16]
  reg  [127:0]    s7_dat;	// @[Reg.scala:19:16]
  reg  [1:0]      s3_bypass_data_REG;	// @[SourceD.scala:337:19]
  reg  [127:0]    s3_bypass_data_REG_1;	// @[SourceD.scala:337:66]
  assign _s3_bypass_data_T_24 = s3_bypass_data_REG[0] ? _atomics_io_data_out[63:0] : s3_bypass_data_REG_1[63:0];	// @[SourceD.scala:207:78, :208:78, :210:75, :258:23, :337:{19,66}]
  assign _s3_bypass_data_T_25 = s3_bypass_data_REG[1] ? _atomics_io_data_out[127:64] : s3_bypass_data_REG_1[127:64];	// @[SourceD.scala:207:78, :208:78, :210:75, :258:23, :337:{19,66}]
  assign s1_x_bypass = (s2_req_set == s1_req_set & s2_req_way == s1_req_way & s2_beat == s1_beat & s2_full & s2_retires ? {s2_req_size[2] | s2_req_offset[3], s2_req_size[2] | ~(s2_req_offset[3])} : 2'h0) | (s3_req_set == s1_req_set & s3_req_way == s1_req_way & s3_beat == s1_beat & s3_full & s3_retires ? {s3_req_size[2] | s3_req_offset[3], s3_req_size[2] | ~(s3_req_offset[3])} : 2'h0) | (s4_req_set == s1_req_set & s4_req_way == s1_req_way & s4_beat == s1_beat & s4_full ? {s4_req_size[2] | s4_req_offset[3], s4_req_size[2] | ~(s4_req_offset[3])} : 2'h0);	// @[Cat.scala:33:92, Misc.scala:205:21, :209:26, :210:20, :214:29, Reg.scala:19:16, SourceD.scala:86:27, :88:19, :102:56, :147:24, :190:24, :248:24, :344:{32,61,87,110}, :345:{32,61,87,110}, :346:{32,61,87,99}, :356:24, :357:24, :358:24, :360:44]
  wire            s1_single = s1_req_prio_0 ? s1_req_opcode == 3'h5 | s1_grant : _s1_single_T_2;	// @[SourceD.scala:88:19, :93:{33,76}, :94:66, :98:{22,53,62}]
  wire [12:0]     _s1_beats1_T_1 = 13'h3F << s1_req_size;	// @[SourceD.scala:88:19, package.scala:235:71]
  wire            s1_last = s1_counter == (s1_single ? 2'h0 : ~(_s1_beats1_T_1[5:4]));	// @[SourceD.scala:86:27, :98:22, :101:22, :103:28, package.scala:235:{46,71,76}]
  wire            _T_12 = io_bs_radr_ready & _io_bs_radr_valid_output;	// @[Decoupled.scala:51:35, SourceD.scala:96:56]
  wire            s2_latch = _s1_valid_T & (~_io_bs_radr_valid_output | io_bs_radr_ready) & s2_ready;	// @[SourceD.scala:90:40, :96:56, :129:18, :141:{42,54}, :184:24]
  wire            s3_latch = s2_full & (~s2_valid_pb | pb_ready) & s3_ready;	// @[SourceD.scala:147:24, :148:28, :175:21, :177:18, :183:{27,40}, :242:24]
  wire            s4_latch = s3_valid & s3_retires & s4_ready;	// @[Reg.scala:19:16, SourceD.scala:241:23, :247:41, :293:59]
  wire            retire = s4_full & (io_bs_wadr_ready | ~s4_need_bs);	// @[Reg.scala:19:16, SourceD.scala:248:24, :290:29, :300:{24,45}]
  wire [9:0]      pre_s3_req_set = s3_latch ? s2_req_set : s3_req_set;	// @[Reg.scala:19:16, SourceD.scala:177:18, :315:24]
  wire [2:0]      pre_s3_req_way = s3_latch ? s2_req_way : s3_req_way;	// @[Reg.scala:19:16, SourceD.scala:177:18, :315:24]
  wire            _pre_s3_5_bypass_T = retire ? s4_req_size[2] : s5_req_size[2];	// @[Reg.scala:19:16, SourceD.scala:300:24, :317:24]
  wire            pre_s3_5_bypass_bit = retire ? s4_req_offset[3] : s5_req_offset[3];	// @[Reg.scala:19:16, SourceD.scala:300:24, :317:24]
  wire            _pre_s3_6_bypass_T = retire ? s5_req_size[2] : s6_req_size[2];	// @[Reg.scala:19:16, SourceD.scala:300:24, :318:24]
  wire            pre_s3_6_bypass_bit = retire ? s5_req_offset[3] : s6_req_offset[3];	// @[Reg.scala:19:16, SourceD.scala:300:24, :318:24]
  wire [1:0]      pre_s3_beat = s3_latch ? s2_beat : s3_beat;	// @[Reg.scala:19:16, SourceD.scala:177:18, :319:24]
  wire [127:0]    pre_s5_dat = retire ? _atomics_io_data_out : s5_dat;	// @[Reg.scala:19:16, SourceD.scala:258:23, :300:24, :323:24]
  wire [127:0]    pre_s6_dat = retire ? s5_dat : s6_dat;	// @[Reg.scala:19:16, SourceD.scala:300:24, :324:24]
  wire [127:0]    pre_s7_dat = retire ? s6_dat : s7_dat;	// @[Reg.scala:19:16, SourceD.scala:300:24, :325:24]
  wire [1:0]      pre_s3_5_bypass = (retire ? s4_req_set : s5_req_set) == pre_s3_req_set & (retire ? s4_req_way : s5_req_way) == pre_s3_req_way & (retire ? s4_beat : s5_beat) == pre_s3_beat ? {_pre_s3_5_bypass_T | pre_s3_5_bypass_bit, _pre_s3_5_bypass_T | ~pre_s3_5_bypass_bit} : 2'h0;	// @[Cat.scala:33:92, Misc.scala:210:20, :214:29, Reg.scala:19:16, SourceD.scala:86:27, :300:24, :315:24, :317:24, :319:24, :321:24, :329:{40,77,96,111}, :333:28]
  wire [1:0]      pre_s3_6_bypass = (retire ? s5_req_set : s6_req_set) == pre_s3_req_set & (retire ? s5_req_way : s6_req_way) == pre_s3_req_way & (retire ? s5_beat : s6_beat) == pre_s3_beat ? {_pre_s3_6_bypass_T | pre_s3_6_bypass_bit, _pre_s3_6_bypass_T | ~pre_s3_6_bypass_bit} : 2'h0;	// @[Cat.scala:33:92, Misc.scala:210:20, :214:29, Reg.scala:19:16, SourceD.scala:86:27, :300:24, :315:24, :318:24, :319:24, :322:24, :330:{40,77,96,111}, :334:28]
  wire            _pre_s3_4_bypass_T = s4_latch ? s3_req_size[2] : s4_req_size[2];	// @[Reg.scala:19:16, SourceD.scala:247:41, :316:24]
  wire            pre_s3_4_bypass_bit = s4_latch ? s3_req_offset[3] : s4_req_offset[3];	// @[Reg.scala:19:16, SourceD.scala:247:41, :316:24]
  always @(posedge clock) begin
    if (reset) begin
      busy <= 1'h0;	// @[SourceD.scala:84:21]
      s1_block_r <= 1'h0;	// @[SourceD.scala:84:21, :85:27]
      s1_counter <= 2'h0;	// @[SourceD.scala:86:27]
      s2_full <= 1'h0;	// @[SourceD.scala:84:21, :147:24]
      s2_valid_pb <= 1'h0;	// @[SourceD.scala:84:21, :148:28]
      s3_full <= 1'h0;	// @[SourceD.scala:84:21, :190:24]
      s3_valid_d <= 1'h0;	// @[SourceD.scala:84:21, :191:27]
      s4_full <= 1'h0;	// @[SourceD.scala:84:21, :248:24]
    end
    else begin
      busy <= ~(s2_latch & s1_last) & (io_req_valid | busy);	// @[SourceD.scala:84:21, :103:28, :128:{23,30}, :129:{18,31}, :132:20, :134:12]
      s1_block_r <= ~s2_latch & (_T_12 | s1_block_r);	// @[Decoupled.scala:51:35, SourceD.scala:85:27, :127:{26,39}, :129:{18,31}, :131:16]
      if (s2_latch) begin	// @[SourceD.scala:129:18]
        if (s1_last)	// @[SourceD.scala:103:28]
          s1_counter <= 2'h0;	// @[SourceD.scala:86:27]
        else	// @[SourceD.scala:103:28]
          s1_counter <= s1_counter + 2'h1;	// @[SourceD.scala:86:27, :130:30, :223:54]
        if (s1_req_prio_0)	// @[SourceD.scala:88:19]
          s2_valid_pb <= ~(s1_req_opcode[2]);	// @[SourceD.scala:88:19, :97:{40,54}, :148:28]
        else	// @[SourceD.scala:88:19]
          s2_valid_pb <= s1_req_opcode[0];	// @[SourceD.scala:88:19, :97:72, :148:28]
      end
      else	// @[SourceD.scala:129:18]
        s2_valid_pb <= ~pb_ready & s2_valid_pb;	// @[SourceD.scala:148:28, :175:21, :176:{19,33}]
      s2_full <= s2_latch | ~s3_latch & s2_full;	// @[SourceD.scala:129:18, :147:24, :177:{18,31,41}, :179:{19,29}]
      s3_full <= s3_latch | ~_T_30 & s3_full;	// @[SourceD.scala:177:18, :190:24, :231:34, :235:{31,41}, :237:{19,29}]
      if (s3_latch)	// @[SourceD.scala:177:18]
        s3_valid_d <= s2_need_d;	// @[Reg.scala:19:16, SourceD.scala:191:27]
      else	// @[SourceD.scala:177:18]
        s3_valid_d <= ~io_d_ready & s3_valid_d;	// @[SourceD.scala:191:27, :234:{18,31}]
      s4_full <= s4_latch | ~(io_bs_wadr_ready | ~s4_need_bs) & s4_full;	// @[Reg.scala:19:16, SourceD.scala:247:41, :248:24, :290:{26,29,42,52}, :291:{19,29}]
    end
    if (~busy & io_req_valid) begin	// @[SourceD.scala:84:21, :87:{43,49}]
      s1_req_reg_prio_0 <= io_req_bits_prio_0;	// @[Reg.scala:19:16]
      s1_req_reg_prio_2 <= io_req_bits_prio_2;	// @[Reg.scala:19:16]
      s1_req_reg_opcode <= io_req_bits_opcode;	// @[Reg.scala:19:16]
      s1_req_reg_param <= io_req_bits_param;	// @[Reg.scala:19:16]
      s1_req_reg_size <= io_req_bits_size;	// @[Reg.scala:19:16]
      s1_req_reg_source <= io_req_bits_source;	// @[Reg.scala:19:16]
      s1_req_reg_offset <= io_req_bits_offset;	// @[Reg.scala:19:16]
      s1_req_reg_put <= io_req_bits_put;	// @[Reg.scala:19:16]
      s1_req_reg_set <= io_req_bits_set;	// @[Reg.scala:19:16]
      s1_req_reg_sink <= io_req_bits_sink;	// @[Reg.scala:19:16]
      s1_req_reg_way <= io_req_bits_way;	// @[Reg.scala:19:16]
      s1_req_reg_bad <= io_req_bits_bad;	// @[Reg.scala:19:16]
    end
    s1_latch_bypass <= ~_s1_valid_T | s2_ready;	// @[SourceD.scala:90:{32,33,40,57}, :184:24]
    if (s1_latch_bypass)	// @[SourceD.scala:90:32]
      s1_bypass_r <= s1_x_bypass;	// @[Reg.scala:19:16, SourceD.scala:360:44]
    queue_io_enq_valid_REG <= _T_12;	// @[Decoupled.scala:51:35, SourceD.scala:121:40]
    queue_io_enq_valid_REG_1 <= queue_io_enq_valid_REG;	// @[SourceD.scala:121:{32,40}]
    if (s2_latch) begin	// @[SourceD.scala:129:18]
      s2_beat <= s1_beat;	// @[Reg.scala:19:16, SourceD.scala:102:56]
      if (s1_latch_bypass)	// @[SourceD.scala:90:32]
        s2_bypass <= s1_x_bypass;	// @[Reg.scala:19:16, SourceD.scala:360:44]
      else	// @[SourceD.scala:90:32]
        s2_bypass <= s1_bypass_r;	// @[Reg.scala:19:16]
      if (busy) begin	// @[SourceD.scala:84:21]
        s2_req_prio_0 <= s1_req_reg_prio_0;	// @[Reg.scala:19:16]
        s2_req_prio_2 <= s1_req_reg_prio_2;	// @[Reg.scala:19:16]
        s2_req_opcode <= s1_req_reg_opcode;	// @[Reg.scala:19:16]
        s2_req_param <= s1_req_reg_param;	// @[Reg.scala:19:16]
        s2_req_size <= s1_req_reg_size;	// @[Reg.scala:19:16]
        s2_req_source <= s1_req_reg_source;	// @[Reg.scala:19:16]
        s2_req_offset <= s1_req_reg_offset;	// @[Reg.scala:19:16]
        s2_req_put <= s1_req_reg_put;	// @[Reg.scala:19:16]
        s2_req_set <= s1_req_reg_set;	// @[Reg.scala:19:16]
        s2_req_sink <= s1_req_reg_sink;	// @[Reg.scala:19:16]
        s2_req_way <= s1_req_reg_way;	// @[Reg.scala:19:16]
        s2_req_bad <= s1_req_reg_bad;	// @[Reg.scala:19:16]
      end
      else begin	// @[SourceD.scala:84:21]
        s2_req_prio_0 <= io_req_bits_prio_0;	// @[Reg.scala:19:16]
        s2_req_prio_2 <= io_req_bits_prio_2;	// @[Reg.scala:19:16]
        s2_req_opcode <= io_req_bits_opcode;	// @[Reg.scala:19:16]
        s2_req_param <= io_req_bits_param;	// @[Reg.scala:19:16]
        s2_req_size <= io_req_bits_size;	// @[Reg.scala:19:16]
        s2_req_source <= io_req_bits_source;	// @[Reg.scala:19:16]
        s2_req_offset <= io_req_bits_offset;	// @[Reg.scala:19:16]
        s2_req_put <= io_req_bits_put;	// @[Reg.scala:19:16]
        s2_req_set <= io_req_bits_set;	// @[Reg.scala:19:16]
        s2_req_sink <= io_req_bits_sink;	// @[Reg.scala:19:16]
        s2_req_way <= io_req_bits_way;	// @[Reg.scala:19:16]
        s2_req_bad <= io_req_bits_bad;	// @[Reg.scala:19:16]
      end
      s2_last <= s1_last;	// @[Reg.scala:19:16, SourceD.scala:103:28]
      s2_need_r <= s1_need_r;	// @[Reg.scala:19:16, SourceD.scala:94:88]
      if (s1_req_prio_0)	// @[SourceD.scala:88:19]
        s2_need_pb <= ~(s1_req_opcode[2]);	// @[Reg.scala:19:16, SourceD.scala:88:19, :97:{40,54}]
      else	// @[SourceD.scala:88:19]
        s2_need_pb <= s1_req_opcode[0];	// @[Reg.scala:19:16, SourceD.scala:88:19, :97:72]
      s2_retires <= ~s1_single;	// @[Reg.scala:19:16, SourceD.scala:98:22, :99:20]
      s2_need_d <= ~(s1_req_prio_0 ? ~(s1_req_opcode[2]) : s1_req_opcode[0]) | s1_counter == 2'h0;	// @[Reg.scala:19:16, SourceD.scala:86:27, :88:19, :97:{23,40,54,72}, :104:29, :156:{29,41}]
    end
    if (s2_valid_pb) begin	// @[SourceD.scala:148:28]
      if (s2_req_prio_0) begin	// @[Reg.scala:19:16]
        s2_pdata_r_data <= io_pb_beat_data;	// @[Reg.scala:19:16]
        s2_pdata_r_mask <= io_pb_beat_mask;	// @[Reg.scala:19:16]
        s2_pdata_r_corrupt <= io_pb_beat_corrupt;	// @[Reg.scala:19:16]
      end
      else begin	// @[Reg.scala:19:16]
        s2_pdata_r_data <= io_rel_beat_data;	// @[Reg.scala:19:16]
        s2_pdata_r_mask <= 16'hFFFF;	// @[Reg.scala:19:16, SourceD.scala:161:64]
        s2_pdata_r_corrupt <= io_rel_beat_corrupt;	// @[Reg.scala:19:16]
      end
    end
    if (s3_latch) begin	// @[SourceD.scala:177:18]
      s3_beat <= s2_beat;	// @[Reg.scala:19:16]
      s3_bypass <= s2_bypass;	// @[Reg.scala:19:16]
      s3_req_prio_0 <= s2_req_prio_0;	// @[Reg.scala:19:16]
      s3_req_prio_2 <= s2_req_prio_2;	// @[Reg.scala:19:16]
      s3_req_opcode <= s2_req_opcode;	// @[Reg.scala:19:16]
      s3_req_param <= s2_req_param;	// @[Reg.scala:19:16]
      s3_req_size <= s2_req_size;	// @[Reg.scala:19:16]
      s3_req_source <= s2_req_source;	// @[Reg.scala:19:16]
      s3_req_offset <= s2_req_offset;	// @[Reg.scala:19:16]
      s3_req_set <= s2_req_set;	// @[Reg.scala:19:16]
      s3_req_sink <= s2_req_sink;	// @[Reg.scala:19:16]
      s3_req_way <= s2_req_way;	// @[Reg.scala:19:16]
      s3_req_bad <= s2_req_bad;	// @[Reg.scala:19:16]
      if (s2_valid_pb) begin	// @[SourceD.scala:148:28]
        if (s2_req_prio_0) begin	// @[Reg.scala:19:16]
          s3_pdata_data <= io_pb_beat_data;	// @[Reg.scala:19:16]
          s3_pdata_mask <= io_pb_beat_mask;	// @[Reg.scala:19:16]
          s3_pdata_corrupt <= io_pb_beat_corrupt;	// @[Reg.scala:19:16]
        end
        else begin	// @[Reg.scala:19:16]
          s3_pdata_data <= io_rel_beat_data;	// @[Reg.scala:19:16]
          s3_pdata_mask <= 16'hFFFF;	// @[Reg.scala:19:16, SourceD.scala:161:64]
          s3_pdata_corrupt <= io_rel_beat_corrupt;	// @[Reg.scala:19:16]
        end
      end
      else begin	// @[SourceD.scala:148:28]
        s3_pdata_data <= s2_pdata_r_data;	// @[Reg.scala:19:16]
        s3_pdata_mask <= s2_pdata_r_mask;	// @[Reg.scala:19:16]
        s3_pdata_corrupt <= s2_pdata_r_corrupt;	// @[Reg.scala:19:16]
      end
      s3_need_bs <= s2_need_pb;	// @[Reg.scala:19:16]
      s3_retires <= s2_retires;	// @[Reg.scala:19:16]
      s3_need_r <= s2_need_r;	// @[Reg.scala:19:16]
    end
    if (s4_latch) begin	// @[SourceD.scala:247:41]
      s4_beat <= s3_beat;	// @[Reg.scala:19:16]
      s4_need_bs <= s3_need_bs;	// @[Reg.scala:19:16]
      s4_need_pb <= s3_need_bs;	// @[Reg.scala:19:16]
      s4_req_prio_2 <= s3_req_prio_2;	// @[Reg.scala:19:16]
      s4_req_param <= s3_req_param;	// @[Reg.scala:19:16]
      s4_req_size <= s3_req_size;	// @[Reg.scala:19:16]
      s4_req_offset <= s3_req_offset;	// @[Reg.scala:19:16]
      s4_req_set <= s3_req_set;	// @[Reg.scala:19:16]
      s4_req_way <= s3_req_way;	// @[Reg.scala:19:16]
      if (s3_req_bad)	// @[Reg.scala:19:16]
        s4_adjusted_opcode <= 3'h4;	// @[Misc.scala:205:21, Reg.scala:19:16]
      else	// @[Reg.scala:19:16]
        s4_adjusted_opcode <= s3_req_opcode;	// @[Reg.scala:19:16]
      s4_pdata_data <= s3_pdata_data;	// @[Reg.scala:19:16]
      s4_pdata_mask <= s3_pdata_mask;	// @[Reg.scala:19:16]
      s4_pdata_corrupt <= s3_pdata_corrupt;	// @[Reg.scala:19:16]
      s4_rdata <= d_bits_data;	// @[Cat.scala:33:92, Reg.scala:19:16]
    end
    if (retire) begin	// @[SourceD.scala:300:24]
      s5_req_size <= s4_req_size;	// @[Reg.scala:19:16]
      s5_req_offset <= s4_req_offset;	// @[Reg.scala:19:16]
      s5_req_set <= s4_req_set;	// @[Reg.scala:19:16]
      s5_req_way <= s4_req_way;	// @[Reg.scala:19:16]
      s5_beat <= s4_beat;	// @[Reg.scala:19:16]
      s5_dat <= _atomics_io_data_out;	// @[Reg.scala:19:16, SourceD.scala:258:23]
      s6_req_size <= s5_req_size;	// @[Reg.scala:19:16]
      s6_req_offset <= s5_req_offset;	// @[Reg.scala:19:16]
      s6_req_set <= s5_req_set;	// @[Reg.scala:19:16]
      s6_req_way <= s5_req_way;	// @[Reg.scala:19:16]
      s6_beat <= s5_beat;	// @[Reg.scala:19:16]
      s6_dat <= s5_dat;	// @[Reg.scala:19:16]
      s7_dat <= s6_dat;	// @[Reg.scala:19:16]
    end
    if ((s4_latch ? s3_req_set : s4_req_set) == pre_s3_req_set & (s4_latch ? s3_req_way : s4_req_way) == pre_s3_req_way & (s4_latch ? s3_beat : s4_beat) == pre_s3_beat & (s4_latch | ~(io_bs_wadr_ready | ~s4_need_bs) & s4_full))	// @[Reg.scala:19:16, SourceD.scala:247:41, :248:24, :290:29, :315:24, :316:24, :319:24, :320:24, :326:{30,34,53,69}, :328:{40,77,111,127}]
      s3_bypass_data_REG <= {_pre_s3_4_bypass_T | pre_s3_4_bypass_bit, _pre_s3_4_bypass_T | ~pre_s3_4_bypass_bit};	// @[Cat.scala:33:92, Misc.scala:210:20, :214:29, SourceD.scala:316:24, :337:19]
    else	// @[SourceD.scala:328:127]
      s3_bypass_data_REG <= 2'h0;	// @[SourceD.scala:86:27, :337:19]
    s3_bypass_data_REG_1 <= {pre_s3_5_bypass[1] ? pre_s5_dat[127:64] : pre_s3_6_bypass[1] ? pre_s6_dat[127:64] : pre_s7_dat[127:64], pre_s3_5_bypass[0] ? pre_s5_dat[63:0] : pre_s3_6_bypass[0] ? pre_s6_dat[63:0] : pre_s7_dat[63:0]};	// @[Cat.scala:33:92, SourceD.scala:207:78, :208:78, :210:75, :323:24, :324:24, :325:24, :333:28, :334:28, :337:66]
  end // always @(posedge)
  `ifndef SYNTHESIS
    always @(posedge clock) begin	// @[SourceD.scala:123:10]
      if (~reset & ~(~queue_io_enq_valid_REG_1 | _queue_io_enq_ready)) begin	// @[SourceD.scala:120:21, :121:32, :123:{10,11,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[SourceD.scala:123:10]
          $error("Assertion failed\n    at SourceD.scala:123 assert (!queue.io.enq.valid || queue.io.enq.ready)\n");	// @[SourceD.scala:123:10]
        if (`STOP_COND_)	// @[SourceD.scala:123:10]
          $fatal;	// @[SourceD.scala:123:10]
      end
      if (~reset & ~(~s3_full | ~s3_need_r | _queue_io_deq_valid)) begin	// @[Reg.scala:19:16, SourceD.scala:120:21, :190:24, :232:{10,11,23,34}]
        if (`ASSERT_VERBOSE_COND_)	// @[SourceD.scala:232:10]
          $error("Assertion failed\n    at SourceD.scala:232 assert (!s3_full || !s3_need_r || queue.io.deq.valid)\n");	// @[SourceD.scala:232:10]
        if (`STOP_COND_)	// @[SourceD.scala:232:10]
          $fatal;	// @[SourceD.scala:232:10]
      end
      if (~reset & s4_full & s4_need_pb & s4_pdata_corrupt) begin	// @[Reg.scala:19:16, SourceD.scala:248:24, :277:10]
        if (`ASSERT_VERBOSE_COND_)	// @[SourceD.scala:277:10]
          $error("Assertion failed: Data poisoning unsupported\n    at SourceD.scala:277 assert (!(s4_full && s4_need_pb && s4_pdata.corrupt), \"Data poisoning unsupported\")\n");	// @[SourceD.scala:277:10]
        if (`STOP_COND_)	// @[SourceD.scala:277:10]
          $fatal;	// @[SourceD.scala:277:10]
      end
    end // always @(posedge)
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    logic [31:0] _RANDOM_1;
    logic [31:0] _RANDOM_2;
    logic [31:0] _RANDOM_3;
    logic [31:0] _RANDOM_4;
    logic [31:0] _RANDOM_5;
    logic [31:0] _RANDOM_6;
    logic [31:0] _RANDOM_7;
    logic [31:0] _RANDOM_8;
    logic [31:0] _RANDOM_9;
    logic [31:0] _RANDOM_10;
    logic [31:0] _RANDOM_11;
    logic [31:0] _RANDOM_12;
    logic [31:0] _RANDOM_13;
    logic [31:0] _RANDOM_14;
    logic [31:0] _RANDOM_15;
    logic [31:0] _RANDOM_16;
    logic [31:0] _RANDOM_17;
    logic [31:0] _RANDOM_18;
    logic [31:0] _RANDOM_19;
    logic [31:0] _RANDOM_20;
    logic [31:0] _RANDOM_21;
    logic [31:0] _RANDOM_22;
    logic [31:0] _RANDOM_23;
    logic [31:0] _RANDOM_24;
    logic [31:0] _RANDOM_25;
    logic [31:0] _RANDOM_26;
    logic [31:0] _RANDOM_27;
    logic [31:0] _RANDOM_28;
    logic [31:0] _RANDOM_29;
    logic [31:0] _RANDOM_30;
    logic [31:0] _RANDOM_31;
    logic [31:0] _RANDOM_32;
    logic [31:0] _RANDOM_33;
    logic [31:0] _RANDOM_34;
    logic [31:0] _RANDOM_35;
    logic [31:0] _RANDOM_36;
    logic [31:0] _RANDOM_37;
    logic [31:0] _RANDOM_38;
    logic [31:0] _RANDOM_39;
    logic [31:0] _RANDOM_40;
    logic [31:0] _RANDOM_41;
    logic [31:0] _RANDOM_42;
    logic [31:0] _RANDOM_43;
    logic [31:0] _RANDOM_44;
    logic [31:0] _RANDOM_45;
    logic [31:0] _RANDOM_46;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        _RANDOM_1 = `RANDOM;
        _RANDOM_2 = `RANDOM;
        _RANDOM_3 = `RANDOM;
        _RANDOM_4 = `RANDOM;
        _RANDOM_5 = `RANDOM;
        _RANDOM_6 = `RANDOM;
        _RANDOM_7 = `RANDOM;
        _RANDOM_8 = `RANDOM;
        _RANDOM_9 = `RANDOM;
        _RANDOM_10 = `RANDOM;
        _RANDOM_11 = `RANDOM;
        _RANDOM_12 = `RANDOM;
        _RANDOM_13 = `RANDOM;
        _RANDOM_14 = `RANDOM;
        _RANDOM_15 = `RANDOM;
        _RANDOM_16 = `RANDOM;
        _RANDOM_17 = `RANDOM;
        _RANDOM_18 = `RANDOM;
        _RANDOM_19 = `RANDOM;
        _RANDOM_20 = `RANDOM;
        _RANDOM_21 = `RANDOM;
        _RANDOM_22 = `RANDOM;
        _RANDOM_23 = `RANDOM;
        _RANDOM_24 = `RANDOM;
        _RANDOM_25 = `RANDOM;
        _RANDOM_26 = `RANDOM;
        _RANDOM_27 = `RANDOM;
        _RANDOM_28 = `RANDOM;
        _RANDOM_29 = `RANDOM;
        _RANDOM_30 = `RANDOM;
        _RANDOM_31 = `RANDOM;
        _RANDOM_32 = `RANDOM;
        _RANDOM_33 = `RANDOM;
        _RANDOM_34 = `RANDOM;
        _RANDOM_35 = `RANDOM;
        _RANDOM_36 = `RANDOM;
        _RANDOM_37 = `RANDOM;
        _RANDOM_38 = `RANDOM;
        _RANDOM_39 = `RANDOM;
        _RANDOM_40 = `RANDOM;
        _RANDOM_41 = `RANDOM;
        _RANDOM_42 = `RANDOM;
        _RANDOM_43 = `RANDOM;
        _RANDOM_44 = `RANDOM;
        _RANDOM_45 = `RANDOM;
        _RANDOM_46 = `RANDOM;
        busy = _RANDOM_0[0];	// @[SourceD.scala:84:21]
        s1_block_r = _RANDOM_0[1];	// @[SourceD.scala:84:21, :85:27]
        s1_counter = _RANDOM_0[3:2];	// @[SourceD.scala:84:21, :86:27]
        s1_req_reg_prio_0 = _RANDOM_0[4];	// @[Reg.scala:19:16, SourceD.scala:84:21]
        s1_req_reg_prio_2 = _RANDOM_0[6];	// @[Reg.scala:19:16, SourceD.scala:84:21]
        s1_req_reg_opcode = _RANDOM_0[10:8];	// @[Reg.scala:19:16, SourceD.scala:84:21]
        s1_req_reg_param = _RANDOM_0[13:11];	// @[Reg.scala:19:16, SourceD.scala:84:21]
        s1_req_reg_size = _RANDOM_0[16:14];	// @[Reg.scala:19:16, SourceD.scala:84:21]
        s1_req_reg_source = _RANDOM_0[22:17];	// @[Reg.scala:19:16, SourceD.scala:84:21]
        s1_req_reg_offset = _RANDOM_1[9:4];	// @[Reg.scala:19:16]
        s1_req_reg_put = _RANDOM_1[15:10];	// @[Reg.scala:19:16]
        s1_req_reg_set = _RANDOM_1[25:16];	// @[Reg.scala:19:16]
        s1_req_reg_sink = _RANDOM_1[29:26];	// @[Reg.scala:19:16]
        s1_req_reg_way = {_RANDOM_1[31:30], _RANDOM_2[0]};	// @[Reg.scala:19:16]
        s1_req_reg_bad = _RANDOM_2[1];	// @[Reg.scala:19:16]
        s1_latch_bypass = _RANDOM_2[2];	// @[Reg.scala:19:16, SourceD.scala:90:32]
        s1_bypass_r = _RANDOM_2[4:3];	// @[Reg.scala:19:16]
        queue_io_enq_valid_REG = _RANDOM_2[5];	// @[Reg.scala:19:16, SourceD.scala:121:40]
        queue_io_enq_valid_REG_1 = _RANDOM_2[6];	// @[Reg.scala:19:16, SourceD.scala:121:32]
        s2_full = _RANDOM_2[7];	// @[Reg.scala:19:16, SourceD.scala:147:24]
        s2_valid_pb = _RANDOM_2[8];	// @[Reg.scala:19:16, SourceD.scala:148:28]
        s2_beat = _RANDOM_2[10:9];	// @[Reg.scala:19:16]
        s2_bypass = _RANDOM_2[12:11];	// @[Reg.scala:19:16]
        s2_req_prio_0 = _RANDOM_2[13];	// @[Reg.scala:19:16]
        s2_req_prio_2 = _RANDOM_2[15];	// @[Reg.scala:19:16]
        s2_req_opcode = _RANDOM_2[19:17];	// @[Reg.scala:19:16]
        s2_req_param = _RANDOM_2[22:20];	// @[Reg.scala:19:16]
        s2_req_size = _RANDOM_2[25:23];	// @[Reg.scala:19:16]
        s2_req_source = _RANDOM_2[31:26];	// @[Reg.scala:19:16]
        s2_req_offset = _RANDOM_3[18:13];	// @[Reg.scala:19:16]
        s2_req_put = _RANDOM_3[24:19];	// @[Reg.scala:19:16]
        s2_req_set = {_RANDOM_3[31:25], _RANDOM_4[2:0]};	// @[Reg.scala:19:16]
        s2_req_sink = _RANDOM_4[6:3];	// @[Reg.scala:19:16]
        s2_req_way = _RANDOM_4[9:7];	// @[Reg.scala:19:16]
        s2_req_bad = _RANDOM_4[10];	// @[Reg.scala:19:16]
        s2_last = _RANDOM_4[11];	// @[Reg.scala:19:16]
        s2_need_r = _RANDOM_4[12];	// @[Reg.scala:19:16]
        s2_need_pb = _RANDOM_4[13];	// @[Reg.scala:19:16]
        s2_retires = _RANDOM_4[14];	// @[Reg.scala:19:16]
        s2_need_d = _RANDOM_4[15];	// @[Reg.scala:19:16]
        s2_pdata_r_data = {_RANDOM_4[31:16], _RANDOM_5, _RANDOM_6, _RANDOM_7, _RANDOM_8[15:0]};	// @[Reg.scala:19:16]
        s2_pdata_r_mask = _RANDOM_8[31:16];	// @[Reg.scala:19:16]
        s2_pdata_r_corrupt = _RANDOM_9[0];	// @[Reg.scala:19:16]
        s3_full = _RANDOM_9[1];	// @[Reg.scala:19:16, SourceD.scala:190:24]
        s3_valid_d = _RANDOM_9[2];	// @[Reg.scala:19:16, SourceD.scala:191:27]
        s3_beat = _RANDOM_9[4:3];	// @[Reg.scala:19:16]
        s3_bypass = _RANDOM_9[6:5];	// @[Reg.scala:19:16]
        s3_req_prio_0 = _RANDOM_9[7];	// @[Reg.scala:19:16]
        s3_req_prio_2 = _RANDOM_9[9];	// @[Reg.scala:19:16]
        s3_req_opcode = _RANDOM_9[13:11];	// @[Reg.scala:19:16]
        s3_req_param = _RANDOM_9[16:14];	// @[Reg.scala:19:16]
        s3_req_size = _RANDOM_9[19:17];	// @[Reg.scala:19:16]
        s3_req_source = _RANDOM_9[25:20];	// @[Reg.scala:19:16]
        s3_req_offset = _RANDOM_10[12:7];	// @[Reg.scala:19:16]
        s3_req_set = _RANDOM_10[28:19];	// @[Reg.scala:19:16]
        s3_req_sink = {_RANDOM_10[31:29], _RANDOM_11[0]};	// @[Reg.scala:19:16]
        s3_req_way = _RANDOM_11[3:1];	// @[Reg.scala:19:16]
        s3_req_bad = _RANDOM_11[4];	// @[Reg.scala:19:16]
        s3_pdata_data = {_RANDOM_11[31:6], _RANDOM_12, _RANDOM_13, _RANDOM_14, _RANDOM_15[5:0]};	// @[Reg.scala:19:16]
        s3_pdata_mask = _RANDOM_15[21:6];	// @[Reg.scala:19:16]
        s3_pdata_corrupt = _RANDOM_15[22];	// @[Reg.scala:19:16]
        s3_need_bs = _RANDOM_15[23];	// @[Reg.scala:19:16]
        s3_retires = _RANDOM_15[24];	// @[Reg.scala:19:16]
        s3_need_r = _RANDOM_15[25];	// @[Reg.scala:19:16]
        s4_full = _RANDOM_15[26];	// @[Reg.scala:19:16, SourceD.scala:248:24]
        s4_beat = _RANDOM_15[28:27];	// @[Reg.scala:19:16]
        s4_need_bs = _RANDOM_15[30];	// @[Reg.scala:19:16]
        s4_need_pb = _RANDOM_15[31];	// @[Reg.scala:19:16]
        s4_req_prio_2 = _RANDOM_16[2];	// @[Reg.scala:19:16]
        s4_req_param = _RANDOM_16[9:7];	// @[Reg.scala:19:16]
        s4_req_size = _RANDOM_16[12:10];	// @[Reg.scala:19:16]
        s4_req_offset = _RANDOM_17[5:0];	// @[Reg.scala:19:16]
        s4_req_set = _RANDOM_17[21:12];	// @[Reg.scala:19:16]
        s4_req_way = _RANDOM_17[28:26];	// @[Reg.scala:19:16]
        s4_adjusted_opcode = {_RANDOM_17[31:30], _RANDOM_18[0]};	// @[Reg.scala:19:16]
        s4_pdata_data = {_RANDOM_18[31:1], _RANDOM_19, _RANDOM_20, _RANDOM_21, _RANDOM_22[0]};	// @[Reg.scala:19:16]
        s4_pdata_mask = _RANDOM_22[16:1];	// @[Reg.scala:19:16]
        s4_pdata_corrupt = _RANDOM_22[17];	// @[Reg.scala:19:16]
        s4_rdata = {_RANDOM_22[31:18], _RANDOM_23, _RANDOM_24, _RANDOM_25, _RANDOM_26[17:0]};	// @[Reg.scala:19:16]
        s5_req_size = _RANDOM_26[30:28];	// @[Reg.scala:19:16]
        s5_req_offset = _RANDOM_27[23:18];	// @[Reg.scala:19:16]
        s5_req_set = {_RANDOM_27[31:30], _RANDOM_28[7:0]};	// @[Reg.scala:19:16]
        s5_req_way = _RANDOM_28[14:12];	// @[Reg.scala:19:16]
        s5_beat = _RANDOM_28[17:16];	// @[Reg.scala:19:16]
        s5_dat = {_RANDOM_28[31:18], _RANDOM_29, _RANDOM_30, _RANDOM_31, _RANDOM_32[17:0]};	// @[Reg.scala:19:16]
        s6_req_size = _RANDOM_32[30:28];	// @[Reg.scala:19:16]
        s6_req_offset = _RANDOM_33[23:18];	// @[Reg.scala:19:16]
        s6_req_set = {_RANDOM_33[31:30], _RANDOM_34[7:0]};	// @[Reg.scala:19:16]
        s6_req_way = _RANDOM_34[14:12];	// @[Reg.scala:19:16]
        s6_beat = _RANDOM_34[17:16];	// @[Reg.scala:19:16]
        s6_dat = {_RANDOM_34[31:18], _RANDOM_35, _RANDOM_36, _RANDOM_37, _RANDOM_38[17:0]};	// @[Reg.scala:19:16]
        s7_dat = {_RANDOM_38[31:18], _RANDOM_39, _RANDOM_40, _RANDOM_41, _RANDOM_42[17:0]};	// @[Reg.scala:19:16]
        s3_bypass_data_REG = _RANDOM_42[19:18];	// @[Reg.scala:19:16, SourceD.scala:337:19]
        s3_bypass_data_REG_1 = {_RANDOM_42[31:20], _RANDOM_43, _RANDOM_44, _RANDOM_45, _RANDOM_46[19:0]};	// @[Reg.scala:19:16, SourceD.scala:337:66]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  Queue_56 queue (	// @[SourceD.scala:120:21]
    .clock            (clock),
    .reset            (reset),
    .io_enq_valid     (queue_io_enq_valid_REG_1),	// @[SourceD.scala:121:32]
    .io_enq_bits_data (io_bs_rdat_data),
    .io_deq_ready     (_T_30 & s3_need_r),	// @[Reg.scala:19:16, SourceD.scala:231:{34,46}]
    .io_enq_ready     (_queue_io_enq_ready),
    .io_deq_valid     (_queue_io_deq_valid),
    .io_deq_bits_data (_queue_io_deq_bits_data)
  );
  Atomics atomics (	// @[SourceD.scala:258:23]
    .io_write    (s4_req_prio_2),	// @[Reg.scala:19:16]
    .io_a_opcode (s4_adjusted_opcode),	// @[Reg.scala:19:16]
    .io_a_param  (s4_req_param),	// @[Reg.scala:19:16]
    .io_a_mask   (s4_pdata_mask),	// @[Reg.scala:19:16]
    .io_a_data   (s4_pdata_data),	// @[Reg.scala:19:16]
    .io_data_in  (s4_rdata),	// @[Reg.scala:19:16]
    .io_data_out (_atomics_io_data_out)
  );
  assign io_req_ready = ~busy;	// @[SourceD.scala:84:21, :87:43]
  assign io_d_valid = s3_valid_d;	// @[SourceD.scala:191:27]
  assign io_d_bits_opcode = d_bits_opcode;	// @[SourceD.scala:222:24]
  assign io_d_bits_param = s3_req_prio_0 & (s3_req_opcode == 3'h6 | (&s3_req_opcode)) ? {1'h0, s3_req_param == 3'h0} : 2'h0;	// @[Reg.scala:19:16, SourceD.scala:84:21, :86:27, :93:33, :202:{30,47,64}, :223:{24,40,54,68}, :280:84]
  assign io_d_bits_size = s3_req_size;	// @[Reg.scala:19:16]
  assign io_d_bits_source = s3_req_source;	// @[Reg.scala:19:16]
  assign io_d_bits_sink = s3_req_sink;	// @[Reg.scala:19:16]
  assign io_d_bits_denied = s3_req_bad;	// @[Reg.scala:19:16]
  assign io_d_bits_data = d_bits_data;	// @[Cat.scala:33:92]
  assign io_d_bits_corrupt = s3_req_bad & d_bits_opcode[0];	// @[Reg.scala:19:16, SourceD.scala:222:24, :229:{32,48}]
  assign io_pb_pop_valid = s2_valid_pb & s2_req_prio_0;	// @[Reg.scala:19:16, SourceD.scala:148:28, :164:34]
  assign io_pb_pop_bits_index = s2_req_put;	// @[Reg.scala:19:16]
  assign io_pb_pop_bits_last = s2_last;	// @[Reg.scala:19:16]
  assign io_rel_pop_valid = s2_valid_pb & ~s2_req_prio_0;	// @[Reg.scala:19:16, SourceD.scala:148:28, :167:{35,38}]
  assign io_rel_pop_bits_index = s2_req_put;	// @[Reg.scala:19:16]
  assign io_rel_pop_bits_last = s2_last;	// @[Reg.scala:19:16]
  assign io_bs_radr_valid = _io_bs_radr_valid_output;	// @[SourceD.scala:96:56]
  assign io_bs_radr_bits_way = s1_req_way;	// @[SourceD.scala:88:19]
  assign io_bs_radr_bits_set = s1_req_set;	// @[SourceD.scala:88:19]
  assign io_bs_radr_bits_beat = s1_beat;	// @[SourceD.scala:102:56]
  assign io_bs_radr_bits_mask = s1_mask;	// @[SourceD.scala:92:76]
  assign io_bs_wadr_valid = s4_full & s4_need_bs;	// @[Reg.scala:19:16, SourceD.scala:248:24, :270:31]
  assign io_bs_wadr_bits_way = s4_req_way;	// @[Reg.scala:19:16]
  assign io_bs_wadr_bits_set = s4_req_set;	// @[Reg.scala:19:16]
  assign io_bs_wadr_bits_beat = s4_beat;	// @[Reg.scala:19:16]
  assign io_bs_wadr_bits_mask = {s4_pdata_mask[8] | s4_pdata_mask[9] | s4_pdata_mask[10] | s4_pdata_mask[11] | s4_pdata_mask[12] | s4_pdata_mask[13] | s4_pdata_mask[14] | s4_pdata_mask[15], s4_pdata_mask[0] | s4_pdata_mask[1] | s4_pdata_mask[2] | s4_pdata_mask[3] | s4_pdata_mask[4] | s4_pdata_mask[5] | s4_pdata_mask[6] | s4_pdata_mask[7]};	// @[Cat.scala:33:92, Reg.scala:19:16, SourceD.scala:275:{45,87}]
  assign io_bs_wdat_data = _atomics_io_data_out;	// @[SourceD.scala:258:23]
  assign io_evict_safe = (~busy | io_evict_req_way != s1_req_reg_way | io_evict_req_set != s1_req_reg_set) & (~s2_full | io_evict_req_way != s2_req_way | io_evict_req_set != s2_req_set) & (~s3_full | io_evict_req_way != s3_req_way | io_evict_req_set != s3_req_set) & (~s4_full | io_evict_req_way != s4_req_way | io_evict_req_set != s4_req_set);	// @[Reg.scala:19:16, SourceD.scala:84:21, :87:43, :147:24, :184:15, :190:24, :232:11, :248:24, :293:30, :376:{35,54,74}, :377:{35,54,74}, :378:{35,54,74,90}, :379:{35,54,74}]
  assign io_grant_safe = (~busy | io_grant_req_way != s1_req_reg_way | io_grant_req_set != s1_req_reg_set) & (~s2_full | io_grant_req_way != s2_req_way | io_grant_req_set != s2_req_set) & (~s3_full | io_grant_req_way != s3_req_way | io_grant_req_set != s3_req_set) & (~s4_full | io_grant_req_way != s4_req_way | io_grant_req_set != s4_req_set);	// @[Reg.scala:19:16, SourceD.scala:84:21, :87:43, :147:24, :184:15, :190:24, :232:11, :248:24, :293:30, :383:{35,54,74}, :384:{35,54,74}, :385:{35,54,74,90}, :386:{35,54,74}]
endmodule

