// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module TransposePreloadUnroller(
  input         clock,
                reset,
                io_in_valid,
  input  [6:0]  io_in_bits_cmd_inst_funct,
  input  [63:0] io_in_bits_cmd_rs1,
                io_in_bits_cmd_rs2,
  input  [5:0]  io_in_bits_rob_id_bits,
  input         io_out_ready,
  output        io_in_ready,
                io_out_valid,
  output [6:0]  io_out_bits_cmd_inst_funct,
  output [63:0] io_out_bits_cmd_rs1,
                io_out_bits_cmd_rs2,
  output        io_out_bits_rob_id_valid,
  output [5:0]  io_out_bits_rob_id_bits
);

  wire        _q_io_deq_valid_0;	// @[MultiHeadedQueue.scala:53:19]
  wire        _q_io_deq_valid_1;	// @[MultiHeadedQueue.scala:53:19]
  wire [6:0]  _q_io_deq_bits_0_cmd_inst_funct;	// @[MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_0_cmd_rs1;	// @[MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_0_cmd_rs2;	// @[MultiHeadedQueue.scala:53:19]
  wire        _q_io_deq_bits_0_rob_id_valid;	// @[MultiHeadedQueue.scala:53:19]
  wire [5:0]  _q_io_deq_bits_0_rob_id_bits;	// @[MultiHeadedQueue.scala:53:19]
  wire [6:0]  _q_io_deq_bits_1_cmd_inst_funct;	// @[MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_1_cmd_rs1;	// @[MultiHeadedQueue.scala:53:19]
  wire [63:0] _q_io_deq_bits_1_cmd_rs2;	// @[MultiHeadedQueue.scala:53:19]
  wire [5:0]  _q_io_deq_bits_1_rob_id_bits;	// @[MultiHeadedQueue.scala:53:19]
  reg  [1:0]  state;	// @[TransposePreloadUnroller.scala:26:22]
  wire        _state_T = state == 2'h0;	// @[TransposePreloadUnroller.scala:26:22, :36:71, :79:22]
  wire        first_preload = _q_io_deq_valid_0 & _q_io_deq_bits_0_cmd_inst_funct == 7'h6 & _state_T;	// @[MultiHeadedQueue.scala:53:19, TransposePreloadUnroller.scala:36:{46,62,71}]
  reg         b_transposed_and_ws;	// @[TransposePreloadUnroller.scala:38:32]
  wire        _io_out_valid_output = first_preload ? ~b_transposed_and_ws | _q_io_deq_valid_1 : state[1] | _q_io_deq_valid_0;	// @[MultiHeadedQueue.scala:53:19, Mux.scala:101:16, TransposePreloadUnroller.scala:26:22, :36:62, :38:32, :58:{23,44}, :59:12]
  wire        _T_2 = first_preload & b_transposed_and_ws & _q_io_deq_valid_1 & _q_io_deq_bits_1_cmd_inst_funct == 7'h4;	// @[MultiHeadedQueue.scala:53:19, TransposePreloadUnroller.scala:36:62, :38:32, :39:70, :63:20]
  wire        _state_T_1 = state == 2'h1;	// @[TransposePreloadUnroller.scala:26:22, :64:12, :77:13]
  wire        _GEN = _T_2 | ~_state_T_1;	// @[Mux.scala:101:16, TransposePreloadUnroller.scala:63:20, :64:12]
  wire        _T = io_out_ready & _io_out_valid_output;	// @[Decoupled.scala:51:35, Mux.scala:101:16]
  wire        is_config = _q_io_deq_bits_0_cmd_inst_funct == 7'h0 & _q_io_deq_bits_0_cmd_rs1[1:0] == 2'h0;	// @[MultiHeadedQueue.scala:53:19, TransposePreloadUnroller.scala:54:40, :55:{29,44,63}, :79:22]
  always @(posedge clock) begin
    if (reset)
      state <= 2'h0;	// @[TransposePreloadUnroller.scala:26:22, :79:22]
    else if (~_T | is_config) begin	// @[Decoupled.scala:51:35, TransposePreloadUnroller.scala:26:22, :55:44, :70:22, :71:22]
    end
    else if (_T_2)	// @[TransposePreloadUnroller.scala:63:20]
      state <= 2'h1;	// @[TransposePreloadUnroller.scala:26:22, :77:13]
    else if (|state) begin	// @[TransposePreloadUnroller.scala:26:22, :78:23]
      if (_state_T)	// @[TransposePreloadUnroller.scala:36:71]
        state <= 2'h1;	// @[TransposePreloadUnroller.scala:26:22, :77:13]
      else	// @[TransposePreloadUnroller.scala:36:71]
        state <= {_state_T_1, 1'h0};	// @[TransposePreloadUnroller.scala:26:22, :64:12, :79:22]
    end
    if (_T & is_config & ~(_q_io_deq_bits_0_cmd_rs1[7]))	// @[Decoupled.scala:51:35, MultiHeadedQueue.scala:53:19, TransposePreloadUnroller.scala:38:32, :55:44, :70:22, :71:22, :72:45, :73:{13,32}, :74:29]
      b_transposed_and_ws <= _q_io_deq_bits_0_cmd_rs1[2] & _q_io_deq_bits_0_cmd_rs1[9];	// @[MultiHeadedQueue.scala:53:19, TransposePreloadUnroller.scala:38:32, :74:{79,105,123}]
  end // always @(posedge)
  `ifndef SYNTHESIS
    `ifdef FIRRTL_BEFORE_INITIAL
      `FIRRTL_BEFORE_INITIAL
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM_0;
    initial begin
      `ifdef INIT_RANDOM_PROLOG_
        `INIT_RANDOM_PROLOG_
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT
        _RANDOM_0 = `RANDOM;
        state = _RANDOM_0[1:0];	// @[TransposePreloadUnroller.scala:26:22]
        b_transposed_and_ws = _RANDOM_0[2];	// @[TransposePreloadUnroller.scala:26:22, :38:32]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL
      `FIRRTL_AFTER_INITIAL
    `endif // FIRRTL_AFTER_INITIAL
  `endif // not def SYNTHESIS
  MultiHeadedQueue q (	// @[MultiHeadedQueue.scala:53:19]
    .clock                        (clock),
    .reset                        (reset),
    .io_enq_valid                 (io_in_valid),
    .io_enq_bits_cmd_inst_funct   (io_in_bits_cmd_inst_funct),
    .io_enq_bits_cmd_rs1          (io_in_bits_cmd_rs1),
    .io_enq_bits_cmd_rs2          (io_in_bits_cmd_rs2),
    .io_enq_bits_rob_id_bits      (io_in_bits_rob_id_bits),
    .io_deq_pop                   (_T & ~_T_2 & state != 2'h1),	// @[Decoupled.scala:51:35, TransposePreloadUnroller.scala:26:22, :63:20, :68:{31,66,75}, :77:13]
    .io_enq_ready                 (io_in_ready),
    .io_deq_valid_0               (_q_io_deq_valid_0),
    .io_deq_valid_1               (_q_io_deq_valid_1),
    .io_deq_bits_0_cmd_inst_funct (_q_io_deq_bits_0_cmd_inst_funct),
    .io_deq_bits_0_cmd_rs1        (_q_io_deq_bits_0_cmd_rs1),
    .io_deq_bits_0_cmd_rs2        (_q_io_deq_bits_0_cmd_rs2),
    .io_deq_bits_0_rob_id_valid   (_q_io_deq_bits_0_rob_id_valid),
    .io_deq_bits_0_rob_id_bits    (_q_io_deq_bits_0_rob_id_bits),
    .io_deq_bits_1_cmd_inst_funct (_q_io_deq_bits_1_cmd_inst_funct),
    .io_deq_bits_1_cmd_rs1        (_q_io_deq_bits_1_cmd_rs1),
    .io_deq_bits_1_cmd_rs2        (_q_io_deq_bits_1_cmd_rs2),
    .io_deq_bits_1_rob_id_bits    (_q_io_deq_bits_1_rob_id_bits)
  );
  assign io_out_valid = _io_out_valid_output;	// @[Mux.scala:101:16]
  assign io_out_bits_cmd_inst_funct = _GEN ? _q_io_deq_bits_0_cmd_inst_funct : 7'h5;	// @[MultiHeadedQueue.scala:53:19, Mux.scala:101:16, TransposePreloadUnroller.scala:48:36]
  assign io_out_bits_cmd_rs1 = _T_2 ? _q_io_deq_bits_0_cmd_rs1 : _state_T_1 ? _q_io_deq_bits_1_cmd_rs1 : state == 2'h2 ? {_q_io_deq_bits_0_cmd_rs1[63:32], 32'hFFFFFFFF} : _q_io_deq_bits_0_cmd_rs1;	// @[Cat.scala:33:92, MultiHeadedQueue.scala:53:19, Mux.scala:101:16, TransposePreloadUnroller.scala:26:22, :28:22, :52:52, :63:20, :64:12, :65:12]
  assign io_out_bits_cmd_rs2 = _T_2 ? {_q_io_deq_bits_0_cmd_rs2[63:32], 32'hFFFFFFFF} : _state_T_1 ? _q_io_deq_bits_1_cmd_rs2 : _q_io_deq_bits_0_cmd_rs2;	// @[Cat.scala:33:92, MultiHeadedQueue.scala:53:19, Mux.scala:101:16, TransposePreloadUnroller.scala:28:22, :42:51, :63:20, :64:12]
  assign io_out_bits_rob_id_valid = ~(_T_2 | _state_T_1) & _q_io_deq_bits_0_rob_id_valid;	// @[MultiHeadedQueue.scala:53:19, Mux.scala:101:16, TransposePreloadUnroller.scala:63:20, :64:12]
  assign io_out_bits_rob_id_bits = _GEN ? _q_io_deq_bits_0_rob_id_bits : _q_io_deq_bits_1_rob_id_bits;	// @[MultiHeadedQueue.scala:53:19, Mux.scala:101:16]
endmodule

