// Generated by CIRCT unknown git version
// Standard header to adapt well known macros to our needs.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

module WeightedArbiter(
  input         clock,
                reset,
                io_inA_valid,
  input  [63:0] io_inA_bits_rs1,
                io_inA_bits_rs2,
  input         io_inB_valid,
  input  [63:0] io_inB_bits_rs1,
                io_inB_bits_rs2,
  input         io_forceA,
                io_forceB,
                io_out_ready,
                io_inA_idle,
                io_inB_idle,
  input  [15:0] io_inA_k,
                io_inB_k,
                io_inB_j,
  output        io_inA_ready,
                io_inB_ready,
                io_out_valid,
  output [6:0]  io_out_bits_inst_funct,
  output [63:0] io_out_bits_rs1,
                io_out_bits_rs2
);

  wire _T_7 = io_inA_k > io_inB_k | io_inB_k == 16'h0 & io_inB_j == 16'h0;	// @[WeightedArbiter.scala:57:{25,36,49,57,69}]
  wire _GEN = io_forceB | io_inA_idle;	// @[WeightedArbiter.scala:36:25, :37:12, :38:30, :53:24, :54:14, :55:29]
  wire _GEN_0 = io_inB_idle | ~_T_7;	// @[WeightedArbiter.scala:31:16, :55:29, :56:14, :57:{36,79}, :60:14]
  wire _GEN_1 = io_forceA | ~(_GEN | ~_GEN_0);	// @[WeightedArbiter.scala:34:19, :35:12, :36:25, :37:12, :38:30, :53:24, :54:14, :55:29, :56:14, :57:79]
  `ifndef SYNTHESIS	// @[WeightedArbiter.scala:72:9]
    always @(posedge clock) begin	// @[WeightedArbiter.scala:72:9]
      if (~reset & io_forceA & io_forceB) begin	// @[WeightedArbiter.scala:72:9]
        if (`ASSERT_VERBOSE_COND_)	// @[WeightedArbiter.scala:72:9]
          $error("Assertion failed\n    at WeightedArbiter.scala:72 assert(!(io.forceA && io.forceB))\n");	// @[WeightedArbiter.scala:72:9]
        if (`STOP_COND_)	// @[WeightedArbiter.scala:72:9]
          $fatal;	// @[WeightedArbiter.scala:72:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign io_inA_ready = (io_forceA | ~_GEN & _GEN_0) & io_out_ready;	// @[WeightedArbiter.scala:31:16, :34:19, :35:12, :36:25, :37:12, :38:30, :53:24, :54:14, :55:29, :56:14, :57:79]
  assign io_inB_ready = ~io_forceA & (_GEN | ~io_inB_idle & _T_7) & io_out_ready;	// @[WeightedArbiter.scala:32:16, :34:19, :36:25, :37:12, :38:30, :53:24, :54:14, :55:29, :57:{36,79}]
  assign io_out_valid = _GEN_1 ? io_inA_valid : io_inB_valid;	// @[WeightedArbiter.scala:34:19, :35:12, :36:25]
  assign io_out_bits_inst_funct = _GEN_1 ? 7'h2 : 7'h1;	// @[WeightedArbiter.scala:34:19, :35:12, :36:25]
  assign io_out_bits_rs1 = _GEN_1 ? io_inA_bits_rs1 : io_inB_bits_rs1;	// @[WeightedArbiter.scala:34:19, :35:12, :36:25]
  assign io_out_bits_rs2 = _GEN_1 ? io_inA_bits_rs2 : io_inB_bits_rs2;	// @[WeightedArbiter.scala:34:19, :35:12, :36:25]
endmodule

